apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: go-web-app
  namespace: argocd
spec:
  project: go-web-app
  source:
    repoURL: 'https://github.com/M949939/go-web-app.git'
    targetRevision: HEAD
    path: helm
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
