name: CI/CD

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'helm/**'
      - 'k8s/**'
      - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          check-latest: true

      - name: Prevent toolchain auto-upgrade
        run: go env -w GOTOOLCHAIN=local

      - name: Cache Go modules
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Download deps
        run: go mod download

      - name: Build
        run: go build -o go-web-app

      - name: Test
        run: go test ./...

  push:
    runs-on: ubuntu-latest
    needs: [ build, code-quality ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/go-web-app:${{ github.run_id }}
            ${{ secrets.DOCKERHUB_USERNAME }}/go-web-app:latest

  update-newtag-in-helm-chart:
    runs-on: ubuntu-latest
    needs: push
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Update tag in Helm chart 
        run: |
          sed -i -E "s|(^[[:space:]]*tag:[[:space:]]*).*$|\1\"${{ github.run_id }}\"|" \
            helm/go-web-app-chart/values.yaml

      - name: Configure git & commit if changed
        shell: bash
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add helm/go-web-app-chart/values.yaml


          # commit only when there are staged changes
          if ! git diff --cached --quiet; then
            git commit -m "Update tag in Helm chart to ${{ github.run_id }}"
            git push origin HEAD:${GITHUB_REF#refs/heads/}
          else
            echo "No changes to commit."
          fi
